version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "A123456a!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # network_mode: host  # ✅ correct
    # container_name: backend
    ports:
      - "5000:80"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=mssql;Database=reportsdb;User Id=sa;Password=A123456a!

volumes:
  sql_data:
